import { Router } from 'express';
import adminRouter from './admin.router';
import announcementRouter from './announcement.router';
import authRouter from './auth.router';
import checkinRouter from './checkin.router';
import conferenceRouter from './conference.router';
import documentRouter from './document.router';
import miscRouter from './misc.router';
import organizerRouter from './organizer.router';
import registrationRouter from './registration.router';
import sessionRouter from './session.router';
import speakerRouter from './speaker.router';
import sponsorRouter from './sponsor.router';
import whitelistRouter from './whitelist.router';
const mainRouter = Router();
mainRouter.use('/', authRouter);
mainRouter.use('/auth', authRouter);
mainRouter.use('/', miscRouter);
mainRouter.use('/admin', adminRouter);
mainRouter.use('/conferences', conferenceRouter);
mainRouter.use('/sessions', sessionRouter);
mainRouter.use('/speakers', speakerRouter);
mainRouter.use('/organizers', organizerRouter);
mainRouter.use('/announcements', announcementRouter);
mainRouter.use('/documents', documentRouter);
mainRouter.use('/sponsors', sponsorRouter);
mainRouter.use('/registrations', registrationRouter);
mainRouter.use('/check-ins', checkinRouter);
mainRouter.use('/whitelists', whitelistRouter);
export default mainRouter;
